### ISSUE TITLE
insecure_key failure

### ISSUE THREAD

**Issue by be-codified** [mtmacdonald/docker-laravel#7] opened 2015-06-17 12:35 UTC
Hi,

I am getting an error:

"Warning: Failed to create the file insecure_key: Operation not supported
curl: (23) Failed writing body (0 != 1675)"

What could be wrong?

**Comment by mtmacdonald** [comment] 2015-07-01 11:19
Which operating system are you using? I've tested this on Ubuntu 14.04 LTS with curl 7.35.0 and can't reproduce your issue.

**Comment by mtmacdonald** [comment] 2016-11-25 09:44
Closing this as it is no longer relevant. SSH is removed in docker-laravel 1.4.0 (use docker exec instead to access a container).

**Closed by mtmacdonald** 2016-11-25 09:44 UTC
